### ISSUE TITLE
Header is not responsive

### ISSUE THREAD

**Issue by ghassanmas** [FACK1/Flak#29]
When the screen is small the header class isn't resposive, since the contents of the headers overlaps and the logo disappear,  
https://github.com/FACK1/Flak/blob/e6a3b5396a191aef6f78b058a227fad44bd41a21/css/main.css#L4-L10
You may not need to change these lines, rather to override in `@media only screen and (max-width: 600px)`.

**Comment by RazanTayyem** [comment]
we hide the logo to solve this problem
