### ISSUE TITLE
flak 

### ISSUE THREAD

**Issue by fdo2** [FACK1/Flak#41]
* i didn't find adressing each section a favorable thing, while they have the same thing in the header
* instead of using images for contact section they could use https://fontawesome.com/icons?d=gallery for sites symbols
* & i liked the map idea and their represented pic

**Comment by RazanTayyem** [comment]
we put the comment of every section you can see it in html and css files
we see the icons that uses it our site is more beautiful than your icons in 
https://fontawesome.com/icons?d=gallery
thanks
